version: '3'
services:
  mongos:
    container_name: mongos
    image: mongo
    command: mongos --configdb cfgrs/host.docker.internal:10001,host.docker.internal:10002,host.docker.internal:10003 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 30000:27017